# Generated by Django 3.1.2 on 2020-11-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='door_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('door', 'door'), ('cnc', 'cnc'), ('bigcnc', 'bigcnc'), ('lathe', 'lathe'), ('laser', 'laser'), ('bandsaw', 'bandsaw'), ('mill', 'mill')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='prismo.userprofile')),
            ],
        ),
    ]
