# Generated by Django 3.1.2 on 2020-11-08 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0003_auto_20201108_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
