# Generated by Django 3.1.2 on 2020-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0006_auto_20201108_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
