# Generated by Django 3.1.2 on 2020-11-08 17:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0009_auto_20201108_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), blank=True, default=list, size=32),
        ),
    ]
