# Generated by Django 3.1.2 on 2020-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0010_userprofile_access_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_info',
        ),
    ]
